#############################################################################
# Makefile for building: dzjzsrv
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 7? 3 14:16:48 2023
# Project:  dzjzsrv.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -o Makefile dzjzsrv.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-dzjzprot-dzjzprot-pro \
		sub-dzjzscd-dzjzscd-pro \
		sub-dzjzprotsrv-dzjzprotsrv-pro \
		sub-dzjzscdsrv-dzjzscdsrv-pro \
		sub-dzjzconfig-dzjzconfig-pro \
		sub-restful-restful-pro

dzjzprot/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dzjzprot/ || $(MKDIR) dzjzprot/ 
	cd dzjzprot/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzprot/dzjzprot.pro -o $(MAKEFILE)
sub-dzjzprot-dzjzprot-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dzjzprot/ || $(MKDIR) dzjzprot/ 
	cd dzjzprot/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzprot/dzjzprot.pro -o $(MAKEFILE)
sub-dzjzprot-dzjzprot-pro: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE)
sub-dzjzprot-dzjzprot-pro-make_default: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) 
sub-dzjzprot-dzjzprot-pro-make_first: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) first
sub-dzjzprot-dzjzprot-pro-all: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) all
sub-dzjzprot-dzjzprot-pro-clean: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) clean
sub-dzjzprot-dzjzprot-pro-distclean: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dzjzprot-dzjzprot-pro-install_subtargets: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) install
sub-dzjzprot-dzjzprot-pro-uninstall_subtargets: dzjzprot/$(MAKEFILE) FORCE
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) uninstall
dzjzscd/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dzjzscd/ || $(MKDIR) dzjzscd/ 
	cd dzjzscd/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzscd/dzjzscd.pro -o $(MAKEFILE)
sub-dzjzscd-dzjzscd-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dzjzscd/ || $(MKDIR) dzjzscd/ 
	cd dzjzscd/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzscd/dzjzscd.pro -o $(MAKEFILE)
sub-dzjzscd-dzjzscd-pro: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE)
sub-dzjzscd-dzjzscd-pro-make_default: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) 
sub-dzjzscd-dzjzscd-pro-make_first: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) first
sub-dzjzscd-dzjzscd-pro-all: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) all
sub-dzjzscd-dzjzscd-pro-clean: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) clean
sub-dzjzscd-dzjzscd-pro-distclean: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dzjzscd-dzjzscd-pro-install_subtargets: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) install
sub-dzjzscd-dzjzscd-pro-uninstall_subtargets: dzjzscd/$(MAKEFILE) FORCE
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) uninstall
dzjzprotsrv/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dzjzprotsrv/ || $(MKDIR) dzjzprotsrv/ 
	cd dzjzprotsrv/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzprotsrv/dzjzprotsrv.pro -o $(MAKEFILE)
sub-dzjzprotsrv-dzjzprotsrv-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dzjzprotsrv/ || $(MKDIR) dzjzprotsrv/ 
	cd dzjzprotsrv/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzprotsrv/dzjzprotsrv.pro -o $(MAKEFILE)
sub-dzjzprotsrv-dzjzprotsrv-pro: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE)
sub-dzjzprotsrv-dzjzprotsrv-pro-make_default: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) 
sub-dzjzprotsrv-dzjzprotsrv-pro-make_first: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) first
sub-dzjzprotsrv-dzjzprotsrv-pro-all: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) all
sub-dzjzprotsrv-dzjzprotsrv-pro-clean: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) clean
sub-dzjzprotsrv-dzjzprotsrv-pro-distclean: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dzjzprotsrv-dzjzprotsrv-pro-install_subtargets: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) install
sub-dzjzprotsrv-dzjzprotsrv-pro-uninstall_subtargets: dzjzprotsrv/$(MAKEFILE) FORCE
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) uninstall
dzjzscdsrv/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dzjzscdsrv/ || $(MKDIR) dzjzscdsrv/ 
	cd dzjzscdsrv/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzscdsrv/dzjzscdsrv.pro -o $(MAKEFILE)
sub-dzjzscdsrv-dzjzscdsrv-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dzjzscdsrv/ || $(MKDIR) dzjzscdsrv/ 
	cd dzjzscdsrv/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzscdsrv/dzjzscdsrv.pro -o $(MAKEFILE)
sub-dzjzscdsrv-dzjzscdsrv-pro: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE)
sub-dzjzscdsrv-dzjzscdsrv-pro-make_default: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) 
sub-dzjzscdsrv-dzjzscdsrv-pro-make_first: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) first
sub-dzjzscdsrv-dzjzscdsrv-pro-all: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) all
sub-dzjzscdsrv-dzjzscdsrv-pro-clean: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) clean
sub-dzjzscdsrv-dzjzscdsrv-pro-distclean: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dzjzscdsrv-dzjzscdsrv-pro-install_subtargets: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) install
sub-dzjzscdsrv-dzjzscdsrv-pro-uninstall_subtargets: dzjzscdsrv/$(MAKEFILE) FORCE
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) uninstall
dzjzconfig/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dzjzconfig/ || $(MKDIR) dzjzconfig/ 
	cd dzjzconfig/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzconfig/dzjzconfig.pro -o $(MAKEFILE)
sub-dzjzconfig-dzjzconfig-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dzjzconfig/ || $(MKDIR) dzjzconfig/ 
	cd dzjzconfig/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/dzjzconfig/dzjzconfig.pro -o $(MAKEFILE)
sub-dzjzconfig-dzjzconfig-pro: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE)
sub-dzjzconfig-dzjzconfig-pro-make_default: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) 
sub-dzjzconfig-dzjzconfig-pro-make_first: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) first
sub-dzjzconfig-dzjzconfig-pro-all: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) all
sub-dzjzconfig-dzjzconfig-pro-clean: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) clean
sub-dzjzconfig-dzjzconfig-pro-distclean: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dzjzconfig-dzjzconfig-pro-install_subtargets: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) install
sub-dzjzconfig-dzjzconfig-pro-uninstall_subtargets: dzjzconfig/$(MAKEFILE) FORCE
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) uninstall
restful/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) restful/ || $(MKDIR) restful/ 
	cd restful/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/restful/restful.pro -o $(MAKEFILE)
sub-restful-restful-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) restful/ || $(MKDIR) restful/ 
	cd restful/ && $(QMAKE) /mnt/hgfs/DF1900/source/dzjzsrv/restful/restful.pro -o $(MAKEFILE)
sub-restful-restful-pro: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE)
sub-restful-restful-pro-make_default: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) 
sub-restful-restful-pro-make_first: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) first
sub-restful-restful-pro-all: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) all
sub-restful-restful-pro-clean: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) clean
sub-restful-restful-pro-distclean: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) distclean
sub-restful-restful-pro-install_subtargets: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) install
sub-restful-restful-pro-uninstall_subtargets: restful/$(MAKEFILE) FORCE
	cd restful/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: dzjzsrv.pro  /usr/local/Trolltech/Qt-4.8.6/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile dzjzsrv.pro
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile dzjzsrv.pro

qmake_all: sub-dzjzprot-dzjzprot-pro-qmake_all sub-dzjzscd-dzjzscd-pro-qmake_all sub-dzjzprotsrv-dzjzprotsrv-pro-qmake_all sub-dzjzscdsrv-dzjzscdsrv-pro-qmake_all sub-dzjzconfig-dzjzconfig-pro-qmake_all sub-restful-restful-pro-qmake_all FORCE

make_default: sub-dzjzprot-dzjzprot-pro-make_default sub-dzjzscd-dzjzscd-pro-make_default sub-dzjzprotsrv-dzjzprotsrv-pro-make_default sub-dzjzscdsrv-dzjzscdsrv-pro-make_default sub-dzjzconfig-dzjzconfig-pro-make_default sub-restful-restful-pro-make_default FORCE
make_first: sub-dzjzprot-dzjzprot-pro-make_first sub-dzjzscd-dzjzscd-pro-make_first sub-dzjzprotsrv-dzjzprotsrv-pro-make_first sub-dzjzscdsrv-dzjzscdsrv-pro-make_first sub-dzjzconfig-dzjzconfig-pro-make_first sub-restful-restful-pro-make_first FORCE
all: sub-dzjzprot-dzjzprot-pro-all sub-dzjzscd-dzjzscd-pro-all sub-dzjzprotsrv-dzjzprotsrv-pro-all sub-dzjzscdsrv-dzjzscdsrv-pro-all sub-dzjzconfig-dzjzconfig-pro-all sub-restful-restful-pro-all FORCE
clean: sub-dzjzprot-dzjzprot-pro-clean sub-dzjzscd-dzjzscd-pro-clean sub-dzjzprotsrv-dzjzprotsrv-pro-clean sub-dzjzscdsrv-dzjzscdsrv-pro-clean sub-dzjzconfig-dzjzconfig-pro-clean sub-restful-restful-pro-clean FORCE
distclean: sub-dzjzprot-dzjzprot-pro-distclean sub-dzjzscd-dzjzscd-pro-distclean sub-dzjzprotsrv-dzjzprotsrv-pro-distclean sub-dzjzscdsrv-dzjzscdsrv-pro-distclean sub-dzjzconfig-dzjzconfig-pro-distclean sub-restful-restful-pro-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-dzjzprot-dzjzprot-pro-install_subtargets sub-dzjzscd-dzjzscd-pro-install_subtargets sub-dzjzprotsrv-dzjzprotsrv-pro-install_subtargets sub-dzjzscdsrv-dzjzscdsrv-pro-install_subtargets sub-dzjzconfig-dzjzconfig-pro-install_subtargets sub-restful-restful-pro-install_subtargets FORCE
uninstall_subtargets: sub-dzjzprot-dzjzprot-pro-uninstall_subtargets sub-dzjzscd-dzjzscd-pro-uninstall_subtargets sub-dzjzprotsrv-dzjzprotsrv-pro-uninstall_subtargets sub-dzjzscdsrv-dzjzscdsrv-pro-uninstall_subtargets sub-dzjzconfig-dzjzconfig-pro-uninstall_subtargets sub-restful-restful-pro-uninstall_subtargets FORCE

sub-dzjzprot-dzjzprot-pro-check: dzjzprot/$(MAKEFILE)
	cd dzjzprot/ && $(MAKE) -f $(MAKEFILE) check
sub-dzjzscd-dzjzscd-pro-check: dzjzscd/$(MAKEFILE)
	cd dzjzscd/ && $(MAKE) -f $(MAKEFILE) check
sub-dzjzprotsrv-dzjzprotsrv-pro-check: dzjzprotsrv/$(MAKEFILE)
	cd dzjzprotsrv/ && $(MAKE) -f $(MAKEFILE) check
sub-dzjzscdsrv-dzjzscdsrv-pro-check: dzjzscdsrv/$(MAKEFILE)
	cd dzjzscdsrv/ && $(MAKE) -f $(MAKEFILE) check
sub-dzjzconfig-dzjzconfig-pro-check: dzjzconfig/$(MAKEFILE)
	cd dzjzconfig/ && $(MAKE) -f $(MAKEFILE) check
sub-restful-restful-pro-check: restful/$(MAKEFILE)
	cd restful/ && $(MAKE) -f $(MAKEFILE) check
check: sub-dzjzprot-dzjzprot-pro-check sub-dzjzscd-dzjzscd-pro-check sub-dzjzprotsrv-dzjzprotsrv-pro-check sub-dzjzscdsrv-dzjzscdsrv-pro-check sub-dzjzconfig-dzjzconfig-pro-check sub-restful-restful-pro-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

